-- 코드를 입력하세요
# 22년 3월의 오프라인/온라인 테이블에서 SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 출력
# JOIN KEY : PRODUCT_ID
# SALES_AMOUNT : 온라인 + 오프라인
# 오프라인 테이블에서 USER_ID 값은 NULL
## 판매일 오름차순 => 상품 ID 오름차순 => 유저 ID 오름차순 정렬
# 두 테이블을 동시에 보여주는 방법은?

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE
       , PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE "2022-03%"
UNION
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE
       , PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE "2022-03%"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID