-- 코드를 입력하세요
# 
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) as SCORE
FROM REST_INFO JOIN REST_REVIEW R USING(REST_ID)
WHERE ADDRESS like "서울%"
GROUP BY REST_ID
ORDER BY ROUND(AVG(REVIEW_SCORE), 2) desc, FAVORITES desc