# 평균 대여 기간이 7일 이상인 자동차
# 평균 대여 기간(컬럼명: AVERAGE_DURATION)
## 소수점 두번째 자리에서 반올림
# 평균 대여 기간 desc, 자동차 ID desc
SELECT CAR_ID, ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1), 1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID having AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION desc, CAR_ID desc