-- 코드를 입력하세요
# 두 테이블에서 22년 10월에 작성된
# 댓글 작성일 - 오름차순, 게시글 제목 - 오름차순
SELECT TITLE, BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R USING(BOARD_ID)
WHERE B.CREATED_DATE LIKE "2022-10%"
ORDER BY R.CREATED_DATE, TITLE
# FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R