# 22년 1월(SALES_DATE)의 카테고리 별(GROUP BY) 도서 판매량(SALES) 합산(SUM)
# 카테고리명 - 오름차순
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES
FROM BOOK join BOOK_SALES using(BOOK_ID)
WHERE SALES_DATE like "2022-01%"
GROUP BY CATEGORY
ORDER BY CATEGORY